name: Run tests on push

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Check for test failures
      run: |
        if [ ${{ steps.test.outcome }} == 'failure' ]; then
          echo "Tests failed, cannot push to master branch"
          exit 1
        fi